// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqS9OtqiOC_fzcatiSyFPq_0mieXksCRY',
    appId: '1:22605493460:web:d0582dd3dc54bddda1f741',
    messagingSenderId: '22605493460',
    projectId: 'cerdas-tani',
    authDomain: 'cerdas-tani.firebaseapp.com',
    storageBucket: 'cerdas-tani.firebasestorage.app',
    measurementId: 'G-0KH2YXV9HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgciL60N0QbTkS9DJHlsMiU5EoBhGYDr8',
    appId: '1:22605493460:android:859506cd5cd46f6ca1f741',
    messagingSenderId: '22605493460',
    projectId: 'cerdas-tani',
    storageBucket: 'cerdas-tani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQKMBGIf59-ll2yUDBjgurx0M_vxPXFco',
    appId: '1:22605493460:ios:c2b191f2c6068327a1f741',
    messagingSenderId: '22605493460',
    projectId: 'cerdas-tani',
    storageBucket: 'cerdas-tani.firebasestorage.app',
    iosBundleId: 'com.example.fertilizerCalculatorMobileV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQKMBGIf59-ll2yUDBjgurx0M_vxPXFco',
    appId: '1:22605493460:ios:c2b191f2c6068327a1f741',
    messagingSenderId: '22605493460',
    projectId: 'cerdas-tani',
    storageBucket: 'cerdas-tani.firebasestorage.app',
    iosBundleId: 'com.example.fertilizerCalculatorMobileV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqS9OtqiOC_fzcatiSyFPq_0mieXksCRY',
    appId: '1:22605493460:web:1cf14b8631c0f566a1f741',
    messagingSenderId: '22605493460',
    projectId: 'cerdas-tani',
    authDomain: 'cerdas-tani.firebaseapp.com',
    storageBucket: 'cerdas-tani.firebasestorage.app',
    measurementId: 'G-24BZC8N2F5',
  );
}
